# GitHub Sponsors integration for the AXEM-SX repository.
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

custom:
- "https://www.paypal.com/ncp/payment/C9K22K9F2G7BQ"
